### PR TITLE
update the mapping part

### PR DESCRIPTION
**Pull request by rongboxu**
Hi! I edited some parts of the create_allocation_map.py, so that we can get the map plot by running the code in the notebook. If you have any question, please don't hesitate to let me know!

### CODE REVIEW

**Comment by paddyroddy** [comment]
What version of `pulp` does this need to run? Is it `2.7.0` or a specific branch/commit?

**Comment by paddyroddy** [comment]
> What version of `pulp` does this need to run? Is it `2.7.0` or a specific branch/commit?

Don't worry I sorted this out

**Comment by paddyroddy** [comment]
I've neatened up the notebook and made the plot display in the notebook. Going to merge.

**Comment by rongboxu** [comment]
> > What version of `pulp` does this need to run? Is it `2.7.0` or a specific branch/commit?
> 
> Don't worry I sorted this out

I use 2.6.0, so I think it should work with 2.7.0! And thank you for merging!

**Pull request merged**
